Initial mkdocs setup
ansible/pytest-ansible pull request #199
Opened 2023-10-18 06:43 UTC by cristianonicolai

2023-10-18 08:32 UTC, ssbarnea requested changes
My impression was that the custom CSS and the logos are not needed as they are supposed to be included inside mkdocs-ansible package.

Are you sure that the docs failed to build correctly without them?

2023-10-19 02:21 UTC, cristianonicolai commented
@ssbarnea thanks for the feedback, using the ansible theme avoids having to add those extra assets. I was taking molecule as base, wondering if I should also update it there, wdyt? https://github.com/ansible/molecule/blob/main/mkdocs.yml#L10

2023-10-19 10:47 UTC, ssbarnea commented
> @ssbarnea thanks for the feedback, using the ansible theme avoids having to add those extra assets. I was taking molecule as base, wondering if I should also update it there, wdyt? https://github.com/ansible/molecule/blob/main/mkdocs.yml#L10

Yes. you should update it there too. The reason is because mkdocs integration on molecule preceded creation of mkdocs-ansible theme.

2023-10-19 10:48 UTC, ssbarnea approved these changes

2023-10-19 11:06 UTC, merged